import type { Metadata } from "next";
// Removed Google Font imports to avoid network dependency during build.
// These fonts were previously fetched at build time and caused failures in
// environments without internet access.
// If custom fonts are needed, consider using `next/font/local` with bundled
// font files instead.
import "./globals.css";

// Default system fonts will be used instead of the Geist fonts.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
